### ISSUE TITLE
[ BugFix ] BQuiz Leaderboard Backward Version Compatibility 

### ISSUE THREAD

**Issue by TreavVasu** [ECellNitrr/ECellOfficialApp#117]
### Requirements
- Old model for Bquiz firebase supports email
- New Model Supports Phone Number
- Check if there's phone number available 
   - If no then display email 
 
### Details 
- https://github.com/ECellNitrr/ECellOfficialApp/blob/a371de92e938b2bea40a451643f8082896cd8533/lib/screens/b_quiz/leaderBoard/leader_card.dart#L56

- Replace to something similar to this solution or BETTER one:
  - https://stackoverflow.com/a/73764671

**Comment by kvns07** [comment]
Sir, what do u mean by "Check if there's phone number available"? Every Signup has mandatory phone number requirement and same will be uploaded to cloud firestore so phone number will be available every time.

**Comment by TreavVasu** [comment]
> Sir, what do u mean by "Check if there's phone number available"? Every Signup has mandatory phone number requirement and same will be uploaded to cloud firestore so phone number will be available every time.

- Currently we follow this pattern 

![image](https://user-images.githubusercontent.com/16835617/202868741-feda7ec4-5518-4572-9586-673182f032ee.png)

- And previously there was that schema where instead of phone number there was email
- So if we found that perticular one case we will just handle it.

**Comment by kvns07** [comment]
Ok got it.
