### ISSUE TITLE
[Docs📜]  How To Contribute 

### ISSUE THREAD

**Issue by TreavVasu** [ECellNitrr/ECellOfficialApp#2]
### Describe your problem
How to contribute to an open-source repository?

### Describe your solution 
Creating a file Contribute.md that mentions everything from how to fork to how to manage to raise a pr.
Steps : 
- First Read Resources 
- Create a File 'Contribute.md' 
- Fill it with relevant changes from the reame mentioned in resources
- Make a PR as per the mentioned methods in Readme

### Resources 
-   [Getting started Section of this Readme only](https://github.com/AliceWonderland/hacktoberfest/blob/master/README.md)

**Comment by KumarUtsav1025** [comment]
Sir, I want to work on this issue #2

**Comment by KumarUtsav1025** [comment]
@TreavVasu sir
