### ISSUE TITLE
[ Update ] Ensure local changes 

### ISSUE THREAD

**Issue by TreavVasu** [ECellNitrr/ECellOfficialApp#6]
### Is your feature request related to a problem? Please describe.
Since the main branch has now been again renamed ensure you have made local changes accordingly as per the prompt.

### Describe the solution you'd like
1. Follow the default popup suggested by GitHub
2.  OR you can try any other approach including deleting the local repo and re-cloning it.

### Additional context

- Reach out in case of confusion

### Priority
- Medium
### Complexity
- Easy

**Comment by KumarUtsav1025** [comment]
@TreavVasu Sir, I followed the default popup suggested by Github and have successfully made the necessary changes in my local copy of the project.
