### ISSUE TITLE
[ BugFix ] Question not displayed

### ISSUE THREAD

**Issue by TreavVasu** [ECellNitrr/ECellOfficialApp#92]
### Requirements 
- The question is not being displayed 
- Check what's the error and resolve it.

### Steps to reproduce 
- Login 
- Play Bquiz 
- See Q4 "How tall is mt..." isn't being displayed
- look into it 
### Details 

![image](https://user-images.githubusercontent.com/16835617/200861642-bafc71d5-0558-4cd5-8f8c-b0836efed974.png)
![image](https://user-images.githubusercontent.com/16835617/200862481-523167a7-d6ff-43fe-9bfb-4de2b615ffae.png)

**Comment by NeerajYadu07** [comment]
Sir this issue is now fixed. It occurred because one field was named "questions" instead of "question".

**Comment by NeerajYadu07** [comment]
![Screenshot_2022-11-09-21-21-37-790_com nitrr ecell esummit ecellapp](https://user-images.githubusercontent.com/100270646/200877772-df4fda4e-582e-4cd9-a663-16fc761e9c07.jpg)
